export enum DefaultTaskName {
  SEARCH = "SEARCH",
  FETCH_DATA = "FETCH_DATA",
  FILTER_MODIFIED = "FILTER_MODIFIED",
  PAGINATION_MODIFIED = "PAGINATION_MODIFIED",
}

export enum TASK_STATUS {
  PENDING = "P",
  SUCCESS = "S",
  ERROR = "E"
}